spring.application.name=API-GATEWAY
server.port=8080

spring.cloud.gateway.routes[0].id=DATA-SERVICE
spring.cloud.gateway.routes[0].uri=lb://DATA-SERVICE
spring.cloud.gateway.routes[0].predicates=Path=/data/**

spring.cloud.gateway.routes[1].id=USER-SERVICE
spring.cloud.gateway.routes[1].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[1].predicates=Path=/user/**

spring.cloud.gateway.routes[2].id=ALERT-SERVICE
spring.cloud.gateway.routes[2].uri=lb://ALERT-SERVICE
spring.cloud.gateway.routes[2].predicates=Path=/alert/**

eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=http://eureka:8761/eureka