spring.application.name=API-GATEWAY
server.port=${PORT:8080}

spring.cloud.gateway.routes[0].id=DATA-SERVICE
spring.cloud.gateway.routes[0].uri=${DATA_SERVICE_URL}
spring.cloud.gateway.routes[0].predicates=Path=/data/**

spring.cloud.gateway.routes[1].id=USER-SERVICE
spring.cloud.gateway.routes[1].uri=${USER_SERVICE_URL}
spring.cloud.gateway.routes[1].predicates=Path=/user/**

spring.cloud.gateway.routes[2].id=ALERT-SERVICE
spring.cloud.gateway.routes[2].uri=${ALERT_SERVICE_URL}
spring.cloud.gateway.routes[2].predicates=Path=/alert/**

eureka.client.enabled=false